blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: https://github.com/BetaHuhn/webcrate#readme
    about: Checkout webcrate's documentation.
  - name: ğŸš€ Feature Request
    url: https://github.com/BetaHuhn/webcrate/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/BetaHuhn/webcrate/discussions/new?category=q-a
    about: Ask the community for help