blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: https://webcrate.app/docs
    about: Checkout WebCrate's documentation before opening an issue.
  - name: ğŸ› Bug Report
    url: https://github.com/WebCrateApp/feedback/issues/new?labels=bug,extension&template=bug_report.md
    about: Create a bug report to help us improve
  - name: ğŸš€ Feature Request
    url: https://github.com/WebCrateApp/feedback/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/WebCrateApp/feedback/discussions/new?category=q-a
    about: Ask the community for help
  - name: ğŸ“§ Contact support
    url: https://webcrate.app/contact
    about: Contact WebCrate's support privately